trigger:
- main

pool:
  name: Default  # Uses your self-hosted agent pool

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '18.x'
  displayName: 'Install Node.js'

- script: |
    cd my-app
    npm install
    npm run build
  displayName: 'Build React Frontend'

- script: |
    cd shopping-backend
    npm install
    npm test
  displayName: 'Install & Test Backend'
